// QUERY KEYS
export const QUERY_KEYS = {
  clientList: "client_list",
  companyList: "company_list",
  questionList: "question_list",
  oneQuestion: "one_question",
  faqsList: "faqs_list",
  documentList: "document_list",
  bannerList: "banner_list",
  courseSliderList: "course_slider_list",
  globalSetting: "global_setting",
  courseList: "course_list",
  maturityLevel: "maturity_level",
  clientTheme: "client_theme",
  courseTrendData: "course_trend_data",
  courseTopFive: "course_top_five",
  oneCourse: "one_course",
  banner: "banner",
  courseSlider: "course_slider",
  logout: "logout",
  notificationList: "notification_list",
  notification: "notification",
  notificationCount: "notification_count",
  getOneCompany: "get_one_company",
  pillers: "pillers",
  trainersList: "trainers_list",
  supportTicketCount: "support_ticket_count",
  supportTicketList: "support_ticket_list",
  trainerOrganisationList: "trainer_organisation_list",
  trainerOrganisation: "trainer_organisation",
  userFetch: "user_fetch",
  userList: "user_list",
  userFetchById: "user_Fetch_by_id",
};
